aligningMarker:
  states:
    - {name: findingMarker, config_path: "task_configs/findingMarker.yaml", timeout: 30} # this state is used to find the marker
    - {name: orientingWithMarker, timeout: 30} # this state is used to align the marker

  transitions:
    - { trigger: markerDetectionOn, source: initialized, dest: findingMarker }
    - { trigger: findingMarkerDone, source: findingMarker, dest: orientingWithMarker   } # this state is used to align the marker
    - { trigger: orientingWithMarkerDone, source: orientingWithMarker, dest: done } # this state is used to align the marker
    
    